--- #YAML:1.0
name:              MHonArc
abstract:          Create HTML archives of mail/news messages
version:           2.6.19
authored_by:
  - Earl Hood <mhonarc@mhonarc.org>
license:           gpl
distribution_type: module
requires:
    Fcntl:          0
    File::Basename: 0
    Getopt::Long:   0
    Symbol:         0
    Time::Local:    0
recommends:
    Digest::MD5:    0
    Encode:         0
    File::Temp:     0
    MIME::Base64:   0
    POSIX:          0
keywords:
    - MIME
    - Mail
    - HTML
generated-by: Earl Hood version 2.00
